# Generated by Django 3.2.18 on 2023-05-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230430_1702'),

    ]

    operations = [
        migrations.RemoveField('User', 'is_staff'),
        migrations.RemoveField('User', 'is_superuser'),
    ]
