# Generated by Django 3.2.18 on 2023-05-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230502_1356'),
    ]

    operations = [
    ]
