# Generated by Django 3.2.18 on 2023-05-11 05:00

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20230510_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='image',
            field=models.ImageField(default=1, upload_to='car_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
    ]
