# Generated by Django 3.2.19 on 2023-05-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230511_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='avatar_images/image.jpg', upload_to='avatar_images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default='Da Nang', max_length=100),
            preserve_default=False,
        ),
    ]
