# Generated by Django 3.2.19 on 2023-05-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='cost_per_day',
            new_name='cost_per_hour',
        ),
    ]
