# Generated by Django 3.2.19 on 2023-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_cost_per_day_parkingslot_cost_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_parking',
            field=models.BooleanField(default=False),
        ),
    ]
