# Generated by Django 3.2.19 on 2023-05-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_car_is_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingrecord',
            name='car_number',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('parking_start_time', models.DateTimeField()),
                ('parking_end_time', models.DateTimeField()),
                ('parking_duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method_direct', models.BooleanField(default=False)),
                ('payment_method_online', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('parking_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parkingrecord')),
            ],
        ),
    ]
