# Generated by Django 3.2.19 on 2023-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_invoice_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method_direct',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method_online',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('direct', 'Direct Payment'), ('online', 'Online Payment')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
