# Generated by Django 3.2.19 on 2023-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='register_name',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='car_images/'),
            preserve_default=False,
        ),
    ]
