# Generated by Django 3.2.19 on 2023-05-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20230527_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='extra_fee',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_fee',
        ),
    ]
