# Generated by Django 3.2.19 on 2023-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20230527_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
