# Generated by Django 3.2.19 on 2023-05-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[(1, 'Registered'), (2, 'Unregistered')], max_length=20),
        ),
    ]
